### PR TITLE
Added Abdulwahab Adebowale Ashimi to contributors.md

### PR DESCRIPTION
**Pull request by Ashimi0x**

### CODE REVIEW

**Comment by ibn-ashimi** [comment]
Added Abdulwahab Adebowale Ashimi to Contributors.md

**Comment by nnamdei** [comment]
well done.

**Comment by Ashimi0x** [comment]
Thank you Sir. Please do this mean, I qualify for the next steps?

**Comment by nnamdei** [comment]
This task is just to prepare everybody towards the task for pre-selection as stated in the email. Keep exploring git.

**Pull request closed without merging**
